# Version of docker-compose
version: '3.8'

# Services
services:
  nginx:
    image: nginx                        # name of the image
    container_name: nginx               # name of the container
    networks:
      - inception_network               # name of the network
    depends_on:
      - wordpress                       # wordpress will be started after nginx
    build:
      context: requirements/nginx       # path to the Dockerfile
      dockerfile: Dockerfile            # name of the Dockerfile
    env_file: .env                      # path to the .env file
    ports:
      - "443:443"                       # port mapping
    restart: on-failure                 # restart the container if it fails
    volumes:
      - wordpress:/var/www/wordpress    # path to the volume

  wordpress:
    image: wordpress                    # name of the image
    container_name: wordpress           # name of the container
    env_file: .env                      # path to the .env file
    networks:
      - inception_network               # name of the network
    build:
      context: requirements/wordpress   # path to the Dockerfile
      dockerfile: Dockerfile            # name of the Dockerfile
    depends_on:
      - mariadb                         # mariadb will be started after wordpress
    restart: on-failure                 # restart the container if it fails
    expose:
      - "9000"                          # expose port 9000
    volumes:
      - wordpress:/var/www/wordpress    # path to the volume

  mariadb:
    image: mariadb                      # name of the image
    container_name: mariadb             # name of the container
    networks:
      - inception_network               # name of the network
    build:
      context: requirements/mariadb     # path to the Dockerfile
      dockerfile: Dockerfile            # name of the Dockerfile
    env_file: .env                      # path to the .env file
    restart: on-failure                 # restart the container if it fails
    expose:
      - "3306"                          # expose port 3306
#    volumes:
#      - mariadb:/var/lib/mysql          # path to the volume

## Volumes
volumes:
  wordpress:
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: ${VOLUMES_PATH}/wordpress
  mariadb:
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: ${VOLUMES_PATH}/mysql

# Network
networks:
  inception_network:                      # name of the network
    driver: bridge                        # type of the network

# Build command : docker-compose -p inception up --build -d
# -p : name of the project
# up : create and start the containers
# --build : build the images if they don't exist or if they have been modified
# -d : run the containers in the background
